export default function TermsPage() {
    return (
        <div className="container mx-auto max-w-4xl px-4 py-12">
            <h1 className="mb-8 text-3xl font-bold text-zinc-900 dark:text-zinc-100">Terms and Conditions</h1>
            <div className="prose max-w-none text-zinc-600 dark:prose-invert dark:text-zinc-400">
                <p className="mb-4 text-sm text-zinc-500">Last Updated: {new Date().toLocaleDateString()}</p>

                <h2 className="mt-8 text-xl font-semibold text-zinc-900 dark:text-zinc-100">1. Introduction</h2>
                <p>
                    Welcome to Saraav. By accessing or using our website, mobile application, or any other services (collectively, the "Service"), you agree to be bound by these Terms and Conditions ("Terms"). If you disagree with any part of the terms, you may not access the Service.
                </p>

                <h2 className="mt-8 text-xl font-semibold text-zinc-900 dark:text-zinc-100">2. Nature of Services & Payment</h2>
                <p>
                    <strong>What you are paying for:</strong> The fees charged on Saraav are strictly for:
                </p>
                <ul className="list-disc pl-6 mb-4">
                    <li>The <strong>curation and organization</strong> of university previous year questions (PYQs).</li>
                    <li>The <strong>text-based solutions</strong> generated by our AI and verified by experts.</li>
                    <li>The <strong>platform features</strong>, including progress tracking, notes, and bookmarking tools.</li>
                </ul>
                <p>
                    <strong>Free Supplementary Content:</strong> Any video content embedded on this platform is hosted by YouTube and is provided solely as a <strong>free, supplementary reference</strong>. You are <strong>not</strong> paying for access to these videos. Saraav does not claim ownership of any third-party video content.
                </p>

                <h2 className="mt-8 text-xl font-semibold text-zinc-900 dark:text-zinc-100">3. Third-Party Content (YouTube)</h2>
                <p>
                    Our Service includes embedded videos from YouTube. By using this Service, you acknowledge that:
                </p>
                <ul className="list-disc pl-6">
                    <li>We use the official YouTube Embedded Player.</li>
                    <li>We do not modify, download, or re-host any YouTube videos.</li>
                    <li>Video availability is subject to the original creator's discretion. If a creator removes a video or disables embedding, it will no longer be available on Saraav.</li>
                    <li>By watching these videos, you agree to be bound by the <a href="https://www.youtube.com/t/terms" target="_blank" rel="noopener noreferrer" className="text-indigo-600 hover:underline">YouTube Terms of Service</a>.</li>
                </ul>

                <h2 className="mt-8 text-xl font-semibold text-zinc-900 dark:text-zinc-100">4. Intellectual Property</h2>
                <p>
                    The <strong>text solutions, question organization, structure, and the "Saraav" branding</strong> are the intellectual property of Saraav and are protected by copyright laws. You may not reproduce, distribute, or create derivative works from our original text content without explicit permission.
                </p>

                <h2 className="mt-8 text-xl font-semibold text-zinc-900 dark:text-zinc-100">5. Payments</h2>
                <p>
                    We use Razorpay for processing payments. We/Saraav do not store your card data on our servers. The data is encrypted through the Payment Card Industry Data Security Standard (PCI-DSS) when processing payment.
                </p>

                <h2 className="mt-8 text-xl font-semibold text-zinc-900 dark:text-zinc-100">6. Limitation of Liability</h2>
                <p>
                    In no event shall Saraav, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
                </p>

                <h2 className="mt-8 text-xl font-semibold text-zinc-900 dark:text-zinc-100">7. Changes</h2>
                <p>
                    We reserve the right, at our sole discretion, to modify or replace these Terms at any time.
                </p>
            </div>
        </div>
    );
}